stages:         
  - install
  - build
  - test
  - deploy

cache:
  paths:
    - node_modules/

install:
  stage: install
  image: node:16.13
  tags:
    - gitlab-org
  script:
    - yarn
  artifacts:
    name: '${CI_BUILD_REF}'
    expire_in: 20 mins
    paths:
      - node_modules
  only:
    refs:
      - merge_requests
    variables:
      - $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "dev"

lint:
  stage: lint
  image: node:16.13
  tags:
    - gitlab-org
  script:
    - yarn ci:lint
  only:
    refs:
      - merge_requests
    variables:
      - $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "dev"

build:
  stage: build
  image: node:16.13
  artifacts:
    name: '${CI_BUILD_REF}'
    expire_in: 20 mins
    paths:
      - .next
  tags:
    - gitlab-org
  script:
    - yarn build
  only:
    refs:
      - merge_requests

build-job: # This job runs in the build stage, which runs first.
  stage: build
  script:
    - echo "Compiling the code..."
    - echo "Compile complete."

